[package]

name = "bio"
version = "0.30.1-alpha.0"
authors = ["Johannes Köster <johannes.koester@tu-dortmund.de>"]
description = "A bioinformatics library for Rust. This library provides implementations of many algorithms and data structures that are useful for bioinformatics, but also in other fields."
homepage = "https://rust-bio.github.io"
repository = "https://github.com/rust-bio/rust-bio"
documentation = "https://docs.rs/bio"
readme = "README.md"
license = "MIT"
build = "build.rs"
edition = "2018"

[package.metadata.release]
pre-release-commit-message = "release version {{version}}"
tag-message = "Version {{version}} of Rust-Bio."

[features]
runtime-dispatch-simd = ["bytecount/runtime-dispatch-simd"]
generic-simd = ["bytecount/generic-simd"]

[dependencies]
bytecount = "0.6"
csv = "1.1"
num-traits = "0.2"
num-integer = "0.1"
itertools = "0.8"
itertools-num = "0.1"
bv = { version = "0.11", features = ["serde"] }
bit-set = "0.5"
ndarray= "0.13"
lazy_static = "1.4"
serde = "1.0"
serde_derive = "1.0"
approx = "0.3"
custom_derive = "0.1"
newtype_derive = "0.1"
ordered-float = "1.0"
quick-error = "1.2"
regex = "1.3"
multimap = "0.6"
fxhash = "0.2"
statrs = "0.11"
bio-types = ">=0.5.1"
fnv = "1.0"
strum = "0.16"
strum_macros = "0.16"
snafu = ">= 0.5, <= 0.6"
getset = "0.0.9"

[dependencies.vec_map]
version = "0.8"
features = ["eders"]

[dependencies.petgraph]
version = "0.4"
features = ["stable_graph"]


[dev-dependencies]
criterion = "0.3.1"

[[bench]]
name = "fm_index_plot"
harness = false
